name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Installing dependencies
        run: |
          wget https://github.com/siemens-mobile-hacks/doxygen/releases/download/v1.10.4/doxygen_1.0_amd64.deb
          sudo dpkg -i doxygen_1.0_amd64.deb
          sudo apt-get -y install gcc-arm-none-eabi

      - name: Smoke Test
        run: ./swilib/tools/smoke-test.sh

      - name: Build Docs
        run: ./swilib/tools/gen-docs.sh

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swilib/html/
